### ISSUE TITLE
Was the /stats/scoreboard API issue resolved in this project?

### ISSUE THREAD

**Issue by bighandsam** [bttmly/nba-client-template#1]
I found this (closed) issue in the Node.js version of this project:

https://github.com/nickb1080/nba/issues/21

Has the same issue been resolved in this simpler version? I'm getting these kinds of errors: "_HTTP Error 400: Bad Request_".

(I've kept endpoint URL as http://stats.nba.com/stats/scoreboard, but does something need to be changed to http://stats.nba.com/scores?)

**Comment by nickb1080** [comment]
The https://github.com/nickb1080/nba repo uses this template directly and does not make any modifications. I've just run the test suite locally and it passes, which means the scoreboard endpoint should work as long as you are using correct headers. In particular, you'll want to use `Referrer` and `User-Agent` that are provided in the template file. The full list of headers used is [here](https://github.com/nickb1080/nba/blob/master/src/get-json.js#L5-L13)
